COMPANY_TICKERS = {
    # Tech Giants
    'alphabet': 'GOOG',
    'google': 'GOOG',
    'apple': 'AAPL',
    'microsoft': 'MSFT',
    'amazon': 'AMZN',
    'meta': 'META',
    'facebook': 'META',
    'netflix': 'NFLX',
    'tesla': 'TSLA',
    'nvidia': 'NVDA',
    'amd': 'AMD',
    'intel': 'INTC',
    'oracle': 'ORCL',
    'salesforce': 'CRM',
    'adobe': 'ADBE',
    'ibm': 'IBM',
    'cisco': 'CSCO',
    'qualcomm': 'QCOM',
    'broadcom': 'AVGO',
    'paypal': 'PYPL',
    'uber': 'UBER',
    'lyft': 'LYFT',
    'airbnb': 'ABNB',
    'spotify': 'SPOT',
    'snap': 'SNAP',
    'snapchat': 'SNAP',
    'twitter': 'TWTR',
    'x corp': 'TWTR',
    'pinterest': 'PINS',
    'zoom': 'ZM',
    'slack': 'WORK',
    'shopify': 'SHOP',
    'square': 'SQ',
    'block': 'SQ',
    'stripe': 'STRIPE',  # Private
    'spacex': 'SPACEX',  # Private

    # Financial Services
    'jpmorgan': 'JPM',
    'jp morgan': 'JPM',
    'bank of america': 'BAC',
    'wells fargo': 'WFC',
    'citigroup': 'C',
    'goldman sachs': 'GS',
    'morgan stanley': 'MS',
    'visa': 'V',
    'mastercard': 'MA',
    'american express': 'AXP',
    'amex': 'AXP',
    'berkshire hathaway': 'BRK.B',
    'berkshire': 'BRK.B',
    'charles schwab': 'SCHW',
    'blackrock': 'BLK',

    # Retail & Consumer
    'walmart': 'WMT',
    'target': 'TGT',
    'costco': 'COST',
    'home depot': 'HD',
    "lowe's": 'LOW',
    'best buy': 'BBY',
    'nike': 'NKE',
    'starbucks': 'SBUX',
    'mcdonalds': 'MCD',
    "mcdonald's": 'MCD',
    'chipotle': 'CMG',
    'coca cola': 'KO',
    'coca-cola': 'KO',
    'pepsi': 'PEP',
    'pepsico': 'PEP',
    'procter & gamble': 'PG',
    'p&g': 'PG',
    'unilever': 'UL',
    'general motors': 'GM',
    'ford': 'F',
    'disney': 'DIS',
    'comcast': 'CMCSA',
    'verizon': 'VZ',
    'at&t': 'T',
    't-mobile': 'TMUS',

    # Healthcare & Pharma
    'pfizer': 'PFE',
    'moderna': 'MRNA',
    'johnson & johnson': 'JNJ',
    'johnson and johnson': 'JNJ',
    'unitedhealth': 'UNH',
    'cvs': 'CVS',
    'walgreens': 'WBA',
    'abbott': 'ABT',
    'merck': 'MRK',
    'eli lilly': 'LLY',
    'bristol myers': 'BMY',
    'abbvie': 'ABBV',

    # Energy
    'exxonmobil': 'XOM',
    'exxon': 'XOM',
    'chevron': 'CVX',
    'conocophillips': 'COP',
    'schlumberger': 'SLB',
    'bp': 'BP',
    'shell': 'SHEL',

    # Industrials & Aerospace
    'boeing': 'BA',
    'lockheed martin': 'LMT',
    'raytheon': 'RTX',
    'general electric': 'GE',
    'ge': 'GE',
    'caterpillar': 'CAT',
    '3m': 'MMM',
    'honeywell': 'HON',
    'deere': 'DE',
    'john deere': 'DE',

    # Semiconductors
    'tsmc': 'TSM',
    'taiwan semiconductor': 'TSM',
    'asml': 'ASML',
    'micron': 'MU',
    'texas instruments': 'TXN',
    'applied materials': 'AMAT',
    'lam research': 'LRCX',
}